import React, { useState, useEffect, } from "react";
import Head from "next/head";
import Layout from "components/layout";
import DangerButton from "components/buttons/DangerButton";
import { fetchPostJSON } from '../../utils/api-helpers'
import { useShoppingCart } from 'use-shopping-cart'

export default function Cart() {
  const [loading, setLoading] = useState(false)
  const [cartEmpty, setCartEmpty] = useState(true)
  const {
    cartCount,
    clearCart,
    cartDetails,
    formattedTotalPrice,
    redirectToCheckout,
  } = useShoppingCart()
  useEffect(() => setCartEmpty(!cartCount), [cartCount])
  const checkout: React.FormEventHandler<HTMLFormElement> = async (event) => {
    event.preventDefault()
    setLoading(true)
    const response = await fetchPostJSON(
      '/api/checkout_sessions/cart',
      cartDetails
      )
      
      if (response.statusCode === 500) {
        console.error(response.message)
        return
      }
      
    redirectToCheckout({ sessionId: response.id })
  }

  return (
    <Layout>
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-row flex-wrap">
        <div className="p-5 w-5/12 m-auto rounded border-solid border-2">
          <h2>カート</h2>

          <div className="flex flex-row justify-between">
            <div className="w-auto">Number of Items</div>
            <div className="w-16 ml-auto">{cartCount}</div>
          </div>

          <div className="flex flex-row justify-between">
            <div className="w-auto">Total</div>
            <div className="w-16 ml-auto">{formattedTotalPrice}</div>
          </div>

          <form className="flex flex-row justify-between" onSubmit={checkout}>
            <button type="submit"
              disabled={cartEmpty || loading}
              className="ml-auto bg-blue-500 text-white px-6 py-2 rounded font-medium mx-3 hover:bg-blue-600 transition duration-200 each-in-out">
              購入
            </button>
            <DangerButton text="空にする" onClickFunction={clearCart} />
          </form>
        </div>
      </div>
    </Layout>
  )
}
