import React, {useState, useEffect, } from "react";
import Head from "next/head";
import Layout from "../../components/layout";
import {
  Grid,
  Card,
  CardContent,
  CardActions,
  Button,
  Divider,
  Typography,
} from '@material-ui/core'
import {fetchPostJSON} from '../../utils/api-helpers'
import {useShoppingCart} from 'use-shopping-cart'

export default function Cart() {
  const [loading, setLoading] = useState(false)
  const [cartEmpty, setCartEmpty] = useState(true)
  const {
    cartCount,
    clearCart,
    cartDetails,
    formattedTotalPrice,
    redirectToCheckout,
  } = useShoppingCart()
  useEffect(() => setCartEmpty(!cartCount), [cartCount])
  const checkout: React.FormEventHandler<HTMLFormElement> = async (event) => {
    event.preventDefault()
    setLoading(true)
    const response = await fetchPostJSON(
      '/api/checkout_sessions/cart',
      cartDetails
    )

    if (response.statusCode === 500) {
      console.error(response.message)
      return
    }

    console.log(response.id)
    redirectToCheckout({sessionId: response.id})
  }

  return (
    <Layout>
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <Grid container direction="row" justify="center" alignItems="center">
        <Grid item xs={6}>
          <Card>
            <CardContent>
              <Typography variant="h5" component="h2">
                Cart
              </Typography>
              <Divider/>
              Number of Items: {cartCount}<br/>
              Total: {formattedTotalPrice}
            </CardContent>
            <CardActions>
              <form onSubmit={checkout}>
                <Button size="small" color="primary" type="submit" disabled={cartEmpty || loading}>
                  購入
                </Button>
                <Button size="small" color="primary" onClick={clearCart}>
                  空にする
                </Button>
              </form>
            </CardActions>
          </Card>
        </Grid>
      </Grid>
    </Layout>
  )
}
