import Head from 'next/head'
import {Grid} from '@material-ui/core'
import Product from '../components/product'
import {Fruits} from "../src/Dataset";
import Layout from "../components/layout";

export default function Home() {
  return (
    <Layout>
      <div>
        <Head>
          <title>Mock Shop</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>

        <Grid container spacing={2}>
          {
            Fruits.map((fruit) => {
              return (<Product fruit={fruit} key={fruit.id}/>)
            })
          }
        </Grid>
      </div>
    </Layout>
  )
}
