import Head from 'next/head'
import Card from 'components/card/Card'
import {Fruits} from "src/Dataset";
import Layout from "components/layout";

export default function Home() {
  return (
    <Layout>
      <div>
        <Head>
          <title>Mock Shop</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>

        <div className="flex flex-row flex-wrap">
          {
            Fruits.map((fruit) => {
              return (<Card product={fruit} key={fruit.id}/>)
            })
          }
        </div>
      </div>
    </Layout>
  )
}
